name: Publish docs via GitHub Pages

on:
  push:
    branches:
      # Update docs based on develop to be able to quickly update docs
      - develop

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
          CONFIG_FILE: docs/mkdocs.yml
